# Default values for angelie.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alexismtr/angelie
  pullPolicy: Always
  tag: ""

environment: dev

service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      expose: 80
      target: http
      name: http

# -- use existing secret to set environment variable
# see templates/secret.yaml
existingMqttEnvSecret:
mqtt:
  server: ""
  port: 1883
  topic:
    shared: true
    group: godevice
    name: devices/+/telemetry
  topic_regex: devices/(.*)/telemetry

# -- use existing secret to set environment variable
# see templates/secret.yaml
existingKafkaEnvSecret:
kafka:
  eventhub: false
  topic: new_telemetries
  consumerGroup: angelie-worker
  clientId: angelie-worker-id
  partitionCount: 1
  verbose: false
  server: "" # must be secret
  username: "" # must be secret
  password: "" # must be secret


podAnnotations: {}

resources: {}

nodeSelector: {}

serviceAccount:
  create: false
  name: