# Default values for angelie.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alexismtr/angelie
  pullPolicy: Always
  tag: ""

service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      expose: 80
      target: http
      name: http

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

podAnnotations: {}

resources: {}

nodeSelector: {}

serviceAccount:
  create: false
  name:

environment: dev

dapr:
  enabled: true
  extraAnnotations:
  port: 3500
  app:
    port:
  metrics:
    port: 9090
  log:
    json: false
    level: info
  components:
    # rabbitmq:
    #   spec: |
    #     apiVersion: dapr.io/v1alpha1
    #     kind: Component
    #     metadata:
    #       name: {{ .Values.configuration.pubSub.dapr.pubComponentName }}
    #       namespace: {{ .Release.Namespace }}
    #     spec:
    #       type: pubsub.rabbitmq
    #       version: v1
    #       metadata: # configure depend on implementation

configuration:
  subscribe:
    topic:
      shared: true
      group: angelie_device
      name: devices/+/telemetry
      regex: devices/(.*)/telemetry
    dapr:
      enabled: false
      componentName:
    broker:
      server:
      port: 1883
  publish:
    topic: telemetry
    dapr:
      enabled: true
      componentName:
    broker:
      connectionString:
      secretRef:
