apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "angelie.fullname" . }}
  labels:
    {{- include "angelie.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "angelie.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.dapr.enabled }}
      {{- include "angelie.dapr.annotations" . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "angelie.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 10000
          protocol: TCP
        env:
        - name: ENV
          value: {{ .Values.environment }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-mqtt
        {{- if and .Values.dapr.enabled .Values.configuration.publish.dapr.enabled }}
        - configMapRef:
            name: {{ printf "%s-%s" (include "angelie.fullname" .) "dapr-pub" }}
        {{- end }}
        {{- if and .Values.dapr.enabled .Values.configuration.subscribe.dapr.enabled }}
        - configMapRef:
            name: {{ printf "%s-%s" (include "angelie.fullname" .) "dapr-sub" }}
        {{- else }}
        - secretRef:
            name: {{ printf "%s-%s" (include "angelie.fullname" .) "mqtt" }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}