{{- with .Values.configuration.subscribe }}
{{- if or (not $.Values.dapr.enabled) (not .dapr.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mqtt" (include "angelie.fullname" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "angelie.labels" $ | nindent 4 }}
type: Secret
data:
  MQTT_URL: {{ default "" .broker.server | b64enc | quote }}
{{- end }}
{{- end }}