{{- if empty .Values.existingKafkaEnvSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-kafka" (include "angelie.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "angelie.labels" . | nindent 4 }}
type: Secret
stringData:
  kafka_username: {{ .Values.kafka.username }}
  kafka_password: {{ .Values.kafka.password }}
  kafka_broker: {{ .Values.kafa.server }}
{{- end -}}
---
{{- if empty .Values.existingMqttEnvSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mqtt" (include "angelie.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "angelie.labels" . | nindent 4 }}
type: Secret
stringData:
  mqtt_server: {{ .Values.mqtt.server }}
{{- end -}}