name: Push docker image

on:
  pull_request:
    types: [opened, edited, synchronize]
    paths-ignore:
    - '.devcontainer/**'
    - '.github/CODEOWNERS'
    - 'README.md'
    - 'docs/*'
    branches:
    - main
  release:
    types:
    - created

jobs:
  docker_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Lint go files
        run: |
          go env
          go install golang.org/x/lint/golint
          golint ./...
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexismtr/angelie
          tag_with_ref: true
          add_git_labels: true